### ISSUE TITLE
Cannot delete old billing account after new one is create and activated

### ISSUE THREAD

**Issue by Gusb3ll** [deploys-app/console#17]
I got 2 billing accounts 

![image](https://user-images.githubusercontent.com/77166960/178464468-e2c94eb9-4b11-425d-a88d-05f3ff881c43.png)
in my case, the `Main` account are activated.

If I wanted to delete the `My billing account`
I get this response and then the page freeze 

![image](https://user-images.githubusercontent.com/77166960/178464807-ae4aad21-488f-4b89-b1b4-efb54a4dd8e5.png)

and the response from the api are `{"ok":false,"error":{}}`

**Comment by acoshift** [comment]
Thanks for opening issue. If billing account has any usage data, it can't be deleted.
I'll fix this on api and maybe implement soft delete.

I'll keep this issue open until bugs' fixed.

**Comment by acoshift** [comment]
The issue is fixed from api. Please reopen if it not fix for you.
